{
  "language": "java",
  "group": "stable",
  "dist": "trusty",
  "os": "linux",
  "install": "mvn clean install spring-boot:run -Dspring.profiles.active=dev -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
}